### ISSUE TITLE
[Issue]: Readme

### ISSUE THREAD

**Issue by mael432** [mst2k/programmierprojekt#106]
### User Story

As a User, I want to gain information about executing the application locally. 

### Acceptance Criteria

- a readme file is giving me the needed information
- the readme file is structured providing an easy understanding

### Sprint Ready Checklist

- [x] Acceptance criteria defined
- [x] Team understands acceptance criteria
- [x] Team has defined solution / steps to satisfy acceptance criteria
- [x] Acceptance criteria is verifiable / testable
- [x] External / 3rd Party dependencies identified

### Complexity

None

**Comment by mst2k** [comment]
#144
