### ISSUE TITLE
[User Story]: Impressum

### ISSUE THREAD

**Issue by YHhsos** [mst2k/programmierprojekt#74]
### User Story

As a user i can verify who developed the website. 

### Acceptance Criteria

- [x] a "Impressum" page exists and can be accesed via footer
- [x] the Impressum is filled with information needed the match the requirements of a public website in Germany

### Sprint Ready Checklist

- [x] Acceptance criteria defined
- [x] Team understands acceptance criteria
- [x] Team has defined solution / steps to satisfy acceptance criteria
- [x] Acceptance criteria is verifiable / testable
- [x] External / 3rd Party dependencies identified

### Complexity

None

**Comment by mst2k** [comment]
#150
