### ISSUE TITLE
[User Story]: Datenschutzerklärung

### ISSUE THREAD

**Issue by YHhsos** [mst2k/programmierprojekt#75]
### User Story

As a user i want to access the privacy policy so i can see what data is beeing used for what reasons.

### Acceptance Criteria

- [x] a page "Datenschutzerklärung" exists
- [x] the page contains the needed information to match the DSGVO

### Sprint Ready Checklist

- [x] Acceptance criteria defined
- [x] Team understands acceptance criteria
- [x] Team has defined solution / steps to satisfy acceptance criteria
- [x] Acceptance criteria is verifiable / testable
- [x] External / 3rd Party dependencies identified

### Complexity

None

**Comment by mst2k** [comment]
#150
